export const CONTENT_REPOSITORY = Symbol('CONTENT_REPOSITORY');
export const CONTENT_RESPONSE_STARTER = Symbol('CONTENT_RESPONSE_STARTER');
export const CONTENT_CANDIDATE_GENERATOR = Symbol('CONTENT_CANDIDATE_GENERATOR');
export const CONTENT_ASSIGNMENT_DECIDER = Symbol('CONTENT_ASSIGNMENT_DECIDER');
export const CONTENT_RISK_PRECHECKER = Symbol('CONTENT_RISK_PRECHECKER');
export const CONTENT_PUBLICATION_METRICS_COLLECTOR = Symbol('CONTENT_PUBLICATION_METRICS_COLLECTOR');
