export const WORKFLOW_REPOSITORY = Symbol('WORKFLOW_REPOSITORY');
export const WORKFLOW_MODEL_ADAPTER = Symbol('WORKFLOW_MODEL_ADAPTER');
export const WORKFLOW_LOADER = Symbol('WORKFLOW_LOADER');
export const EVENT_COMMAND_EXECUTOR = Symbol('EVENT_COMMAND_EXECUTOR');
