export const DEFAULT_CONTENT_ACCOUNT_SETTINGS = [
  {
    key: 'respond-with-breaking-brief',
    name: '快讯型',
    description: '把热点压缩为可快速扫描的单一事实更新',
    xAccountId: '@nikalatekickoff',
    type: '基础生产线',
    personaType: '把热点压缩为可快速扫描的单一事实更新',
    skill: 'respond-with-breaking-brief',
  },
  {
    key: 'develop-hotspot-deep-dive',
    name: '长文/深度分析型',
    description: '解释背景、已知与未知、关键影响和后续观察点',
    xAccountId: '@minaafterhrs',
    type: '基础生产线',
    personaType: '解释背景、已知与未知、关键影响和后续观察点',
    skill: 'develop-hotspot-deep-dive',
  },
  {
    key: 'bridge-hotspot-to-product',
    name: '产品承接型',
    description: '以 PredX 产品账号对热点作适当品牌或市场承接',
    xAccountId: '@MilesOnEvek1',
    type: '基础生产线',
    personaType: '以 PredX 产品账号对热点作适当品牌或市场承接',
    skill: 'bridge-hotspot-to-product',
  },
  {
    key: 'nick-preszler',
    name: 'Nick Preszler',
    description: '机制、激励、指标误读和二阶洞察',
    xAccountId: '@NoraPricesux',
    type: '人设账号',
    personaType: '机制、激励、指标误读和二阶洞察',
    skill: 'Nick Preszler',
  },
  {
    key: 'manifold-markets',
    name: 'Manifold Markets',
    description: '社区原生预测问题、参与和规则解释',
    xAccountId: '@SignalKaiPmmur',
    type: '人设账号',
    personaType: '社区原生预测问题、参与和规则解释',
    skill: 'Manifold Markets',
  },
  {
    key: 'watcherguru',
    name: 'WatcherGuru',
    description: '金融、加密、政策和机构性快讯',
    xAccountId: '@Ox_RheaCalder',
    type: '人设账号',
    personaType: '金融、加密、政策和机构性快讯',
    skill: 'WatcherGuru',
  },
  {
    key: 'roh-on-chain',
    name: 'RohOnChain',
    description: '工具、研究、教育路径和资源清单',
    xAccountId: '@JulesTan_sol',
    type: '人设账号',
    personaType: '工具、研究、教育路径和资源清单',
    skill: 'RohOnChain',
  },
  {
    key: 'unusual-whales',
    name: 'Unusual Whales',
    description: '公司、监管、政治、资金与利益后果',
    xAccountId: '@NoraField_btc',
    type: '人设账号',
    personaType: '公司、监管、政治、资金与利益后果',
    skill: 'Unusual Whales',
  },
  {
    key: 'daily-loud',
    name: 'Daily Loud',
    description: '明星、音乐、体育、创作者和病毒事件',
    xAccountId: '@MaraVotes',
    type: '人设账号',
    personaType: '明星、音乐、体育、创作者和病毒事件',
    skill: 'Daily Loud',
  },
  {
    key: 'pubity',
    name: 'Pubity',
    description: '大众化、积极、可分享的成就与事实卡',
    xAccountId: '@MateoMargins',
    type: '人设账号',
    personaType: '大众化、积极、可分享的成就与事实卡',
    skill: 'Pubity',
  },
  {
    key: 'nate-silver',
    name: 'Nate Silver',
    description: '概率校准、基准、激励与可证伪分析',
    xAccountId: '@SashaBlocksPM',
    type: '人设账号',
    personaType: '概率校准、基准、激励与可证伪分析',
    skill: 'Nate Silver',
  },
  {
    key: 'domer',
    name: 'Domer',
    description: '预测市场规则、结算、资金流、异常与复盘',
    xAccountId: '@EliasMightBeWrong',
    type: '人设账号',
    personaType: '预测市场规则、结算、资金流、异常与复盘',
    skill: 'Domer',
  },
] as const;
